### ISSUE TITLE
 Add npm, yarn and pnpm installation mention for JavaScript client installation guide

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#121]
Add npm, yarn and pnpm installation mention for JavaScript client installation guide before this step:

![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/45df610c-4175-4ba9-892f-aa32bc457d5b)

**Comment by 6r1d** [comment]
Actually, I'd like to clarify what this task needs first. @astrokov7 mentioned several distros and package managers, i.e. Red Hat, Ubuntu, Arch, Brew. Because of that, I am thinking we should start with a doc that refers to [`nvm`](https://github.com/nvm-sh/nvm) installation or having Node on a local machine.

Also, since Iroha-Python heavily relies on the Rust code, I'd like to understand how Iroha-Javascript would be developed from now on. We may need to mention Rustup or installation of `rustc` and `Cargo` with a local package manager. Please comment, @0x009922

**Comment by 0x009922** [comment]
@6r1d,

I think it makes sense to add a note like "This guide assumes you are familiar with Node.js and NPM ecosystem". What is the reason to read Iroha-JavaScript guide without that familiarity? Thus, I don't see a reason to describe how to install Node.js.

Same for `yarn`, `npm`, `pnpm` package manager. The packages installation instruction is done accordingly to how nearly all NPM packages are documented. Usually it is not even necessary to mention all kinds of package managers, and the only `npm` (as a standard package manager coming with Node.js) is enough:

```bash
npm i @iroha2/client
```

Also:

> since Iroha-Python heavily relies on the Rust code, I'd like to understand how Iroha-Javascript would be developed from now on

I don't understand this point. `iroha-javascript` development relies on Rust and Cargo installed on the machine. Maybe we should add a section into the [root README](https://github.com/hyperledger/iroha-javascript/blob/iroha2/README.md). But **if you need to use published `@iroha2/*` packages, you don't need Rust to be installed**.

**Comment by 6r1d** [comment]
> But if you need to use published @iroha2/* packages, you don't need Rust to be installed.
Thanks for mentioning this detail!

**Comment by astrokov7** [comment]
@0x009922 Absolutely agree with you, but I want to suggest when we'll mention "This guide assumes you are familiar with Node.js and NPM ecosystem" mention like link to third party guides `Node.js`, `yarn`, `npm`, `pnpm` etc.
