### ISSUE TITLE
To clarify the details on the Client Configuration page

### ISSUE THREAD

**Issue by astrokov7** [hyperledger/iroha-2-docs#170]
![image.png](https://images.zenhubusercontent.com/62ff7ff6035024b7529178f9/42b5e35b-fc67-4c18-a782-6b14c7f1ba46)

Example of default `config.json`

```json
{
  "TORII_API_URL": "http://127.0.0.1:8080",
  "ACCOUNT_ID": {
    "name": "alice",
    "domain_id": {
      "name": "wonderland"
    }
  },
  "BASIC_AUTH": {
    "web_login": "mad_hatter",
    "password": "ilovetea"
  },
  "PUBLIC_KEY": "ed01207233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0",
  "PRIVATE_KEY": {
    "digest_function": "ed25519",
    "payload": "9ac47abf59b356e0bd7dcbbbb4dec080e302156a48ca907e47cb6aea1d32719e7233bfc89dcbd68c19fde6ce6158225298ec1131b6a130d1aeb454c1ab5183c0"
  },
  "LOGGER_CONFIGURATION": {}
}
```

**Comment by 6r1d** [comment]
> Explain why or mention link

This is a tutorial page, not the detailed options, so adding a link to some page with client configuration options would be nice. The question here is whether those would change a lot. If so, it's a page we'll have to update often.

> … incoming and outgoing connections

Here, a link to the options page may be an overlay of backtick syntax, if we add an options page. We can comment on how the Torii name appeared.

> How can I set up an Iroha peer?

We can mention that an Iroha peer is matching an Iroha process. Thus, one container in Iroha `docker-compose.yml` is typically a peer, and some of these contain 4 peers. Otherwise, simply running Iroha process that is configured correctly means having an active peer.

> `http://` or (preferrably) `https://`
> What are bare sockets

I'd say "bare connection". We're using HTTP to connect to Iroha API.
An alternative to that is the [HTTPS](https://en.wikipedia.org/wiki/HTTPS) connection, which wraps HTTP in [SSL](https://en.wikipedia.org/wiki/Transport_Layer_Security#SSL_1.0,_2.0,_and_3.0).

> How can I set up a domain for public blockchains

I believe that this part is related to global DNS, so someone should rent a domain name from a [registrar](https://en.wikipedia.org/wiki/Domain_name_registrar), have a static IP per peer and assign an [A-record](https://www.cloudflare.com/learning/dns/dns-records/dns-a-record/) to said IP.

Otherwise it may be about internal Iroha domains, but I doubt it. You may ask the person wrote this part after checking it with `git blame`. (Probably @outoftardis)

> Add real default config.json example

It'll be best to add this file after the [versioning](https://i.imgur.com/ClEZdiQ.mp4) doc feature is merged: if we take an example from Iroha, it may be fresh and checked.

**Comment by outoftardis** [comment]
> how to set up a peer

I'll link to this page, as setting up peers is part of the registering peers process: https://hyperledger.github.io/iroha-2-docs/guide/configure/register-unregister.html#registering-peers

**Comment by outoftardis** [comment]
> How can I set up a domain for public blockchains

> I believe that this part is related to global DNS, so someone should rent a domain name from a [registrar](https://en.wikipedia.org/wiki/Domain_name_registrar), have a static IP per peer and assign an [A-record](https://www.cloudflare.com/learning/dns/dns-records/dns-a-record/) to said IP.
> Otherwise it may be about internal Iroha domains, but I doubt it. You may ask the person wrote this part after checking it with git blame. (Probably @outoftardis)

It wasn't written by me. 
@appetrosyan can you help with the paragraph below?

> If you are setting up an Iroha peer, you should set up a domain for public blockchains. Bare sockets are enough for a local private deployment.
