### ISSUE TITLE
Add proper codeowners

### ISSUE THREAD

**Issue by appetrosyan** [hyperledger/iroha-2-docs#47]
We wan to have a separation of concerns in this repo so as not to ping someone unnecessarily I propose adding 

@0x009922 as the code owner of the `**/**.js`
@outoftardis, @WRRicht3r  as the code owner of `**/**.md`
and myself as the code owner of `**`.

**Comment by WRRicht3r** [comment]
Sounds good to me.

**Comment by outoftardis** [comment]
Sounds good to me too.

Also I believe it could be just `*.js` and `*.md` without the `**/`

**Comment by 0x009922** [comment]
Mmm, I guess I am responsible for any code in this repo as well, because even `*.md` files are not plain Markdown files and could be extended with some functionality. For example, [queries.md](https://github.com/hyperledger/iroha-2-docs/blob/017527f61b9e43b457f0a1186eff6056a0592de9/src/guide/advanced/queries.md) has some.

Btw, if to keep the initial plan, then not only `*.js`, but also `*.ts`, `*.vue` and... maybe anything which is not `*.md` )

**Comment by outoftardis** [comment]
what about `src/*` and `*.md` for me and @WRRicht3r, `.vitepress/*` and other config files/scripts for @0x009922? 

I think we can manage manually adding @0x009922 as the reviewer when Markdown files contain certain changes that he'd have to approve. I'd choose this approach is there is a limited number of files that contain that type of functionality.

**Comment by 0x009922** [comment]
Also I am responsible for JavaScript guide (`src/guide/javascript.md`), so it might make sense for me to track it automatically too.

**Comment by outoftardis** [comment]
I'll create a pull request for this
